# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MosaicLayout' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MosaicLayout
  pod 'AFNetworking', '~> 4.0'
  pod 'ORStackView'
  pod 'SwiftyJSON'
  pod "FMMosaicLayout"
end
